### ISSUE TITLE
Is their any way to view default look as weekview.. Not the monthview

### ISSUE THREAD

**Issue by sreeji44** [Mozharovsky/CVCalendar#265] opened 2016-03-29 07:20 UTC
i asked this same question but no response...CVCalendarView has a func to do exactly that.  public func changeMode(mode: CalendarMode, completion: () -> () = {}) in this function what want to change ?.... 

and one more thing is in the storyborad i want o display it as weekview.. so how can change that also .. please help that will be more helpful for me ...

**Comment by elsesiy** [comment] 2016-04-11 14:53
Duplicate of #256

**Closed by elsesiy** 2016-04-11 14:53 UTC
