### ISSUE TITLE
supplementaryView shown on wrong day

### ISSUE THREAD

**Issue by DannyJi** [Mozharovsky/CVCalendar#408] opened 2016-12-21 15:06 UTC
![simulator screen shot dec 21 2016 10 06 42 am](https://cloud.githubusercontent.com/assets/5400889/21394129/51a69670-c765-11e6-92aa-53b4c15033d3.png)
- [ X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X] I have verified that I am using the latest version of CVCalendar.
- [ X] I have given my issue a non-generic title.

## Expected Behavior
I modified the demo to show a circle on a specific day (02 Dec 2016).  

This is how the framework worked a few weeks ago.

## Current Behavior
With the modification - The supplementaryView shows on the wrong date (28 Dec 2016)

This was not how this worked just a month ago.  When I upgrade my project that just got approved in the App Store, all my "event" dates are now broken and circling the wrong dates!

## Steps to Reproduce (for bugs)

1. Download the latest demo
2. Replace the func that show random supplementaryViews with a concrete date

```
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        if let convertedDate = dayView.date.convertedDate(calendar: Calendar.current)  {
          
          let cal = Calendar.current
          var components = DateComponents()
          components.day = 2
          components.month = 12
          components.year = 2016
          let testDate = cal.date(from: components )
          
          if testDate == convertedDate {
            return true
          }
          
        }
        
        return false
    }
```
3.  Run the demo and observe date "circled" is not 02 Dec 2016, but 28 Dec 2016
4.

## Context
I discovered this trying to find a work around for issues I uncovered putting the calendar view in a UI Stackview.  First I though my fixes for that issue were causing these random supplementary views to appear.  It was only when I backed out all my changed that I uncovered this one too.

**Comment by schulz89sp** [comment] 2016-12-29 09:06
In CVCalendarDayView.swift

    public func preliminarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.preliminaryView?(shouldDisplayOnDayView: self) , shouldShow {
            if let preView = delegate.preliminaryView?(viewOnDayView: self) {
                preliminaryView?.removeFromSuperview()
                preliminaryView = preView
                weekView.insertSubview(preView, at: 0)   <---- remove weekView
                preView.layer.zPosition = CGFloat(-MAXFLOAT)
            }
        }
        else {
            preliminaryView?.removeFromSuperview()
        }
    }
    
    public func supplementarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.supplementaryView?(shouldDisplayOnDayView: self) ,
            shouldShow {
            if let supView = delegate.supplementaryView?(viewOnDayView: self) {
                supplementaryView?.removeFromSuperview()
                supplementaryView = supView
                weekView.insertSubview(supView, at: 0)   <---- remove weekView
            }
        } else {
            supplementaryView?.removeFromSuperview()
            supplementaryView = nil
        }
}

Hello, I take off "weekView" where I commented on, since it was added to bust me everything in the calendar, so I take it out and everything is ok!
Otherwise the circles are usually earlier this week.

I hope you help and that developers monitor.

**Comment by sry241** [comment] 2017-01-02 14:14
Hey, I have the same problem. If I remove the before described "weekView" from the CVCalendarDayView.swift, it won't has any changes. It would be nice, if someone could take a look at that.

**Comment by sry241** [comment] 2017-01-02 14:32
Another example:
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        if dayView.date.year == 2017 && dayView.date.month == 1 && dayView.date.day == 19 {
            print("19.01.2017")
            return true
        }
}

If I fill the supplementary function with this, the 22.01.2017 is marked.

**Comment by elsesiy** [comment] 2017-01-03 00:42
The lines were just added on Sep, 26th by @ludoded, see  https://github.com/Mozharovsky/CVCalendar/commit/fd8ca84c8bd3682c3615f9f0179d2132d2952633. I haven't had the time to test the provided data, but may he can give you guys some insight what he tried to fix?

**Comment by DannyJi** [comment] 2017-01-03 18:07
I am using @sry241 example and getting the same results.  My app that was approved mid-Dec 2016, used a pod install/update from early/mid November 2016 (I had pod 'CVCalendar', '~> 1.4.0').  Thankfully, where I use the supplementaryView, my event dates are being marked correctly in production.

I see what @ludoded added in 26 Sept.  I am more suspicious of the [5135825](https://github.com/Mozharovsky/CVCalendar/commit/51358252404063bdcdbbf96fe3a21873134a0432) change since it added the private ivars for supplementaryView and methods @schulz89sp identified - just a hunch.

**Comment by elsesiy** [comment] 2017-01-03 18:12
Okay that change was made by @justinctlam. Any ideas?

**Comment by DannyJi** [comment] 2017-01-03 20:05
@sry241 ... hey I just tried your code.  I did not get 22.01.2017 (22-Jan-2017) marked... but now 13-Feb-2017.

Your print line is coming out in the debugger "19.01.2017".  Strange... I have been trying different past commits and seem like I am getting different results.  So strange.  @elsesiy no clue yet.  I just want to find a stable commit that shows this working, but getting tripped up.

![screen shot 2017-01-03 at 3 03 21 pm](https://cloud.githubusercontent.com/assets/5400889/21621210/f7e9a0da-d1c5-11e6-97e9-5a9fa044f197.png)

**Comment by schulz89sp** [comment] 2017-01-03 20:45
Hello, I tried to use the latest version of CVCalendar with my changes and example proposed above.
So it works for me, I attach images.
<img width="1036" alt="schermata 2017-01-03 alle 21 32 55" src="https://cloud.githubusercontent.com/assets/18734273/21622414/9d0f307a-d1fd-11e6-9087-0a3fa2a3bc94.png">
CVCalendarDayView:
    public func preliminarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.preliminaryView?(shouldDisplayOnDayView: self) , shouldShow {
            if let preView = delegate.preliminaryView?(viewOnDayView: self) {
                preliminaryView?.removeFromSuperview()
                preliminaryView = preView
                weekView.insertSubview(preView, at: 0)
                preView.layer.zPosition = CGFloat(-MAXFLOAT)
            }
        }
        else {
            preliminaryView?.removeFromSuperview()
        }
    }
    
    public func supplementarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.supplementaryView?(shouldDisplayOnDayView: self) ,
            shouldShow {
            if let supView = delegate.supplementaryView?(viewOnDayView: self) {
                supplementaryView?.removeFromSuperview()
                supplementaryView = supView
                insertSubview(supView, at: 0)
            }
        } else {
            supplementaryView?.removeFromSuperview()
            supplementaryView = nil
        }
    }

**Comment by schulz89sp** [comment] 2017-01-03 20:48
Hello, I tried to use the latest version of CVCalendar with my changes and example proposed above.
So it works for me, I attach images.

<img width="1036" alt="schermata 2017-01-03 alle 21 32 55" src="https://cloud.githubusercontent.com/assets/18734273/21622530/370f3bca-d1fe-11e6-8138-1c4fbc3f1361.png">
CVCalendarDayView:

    public func preliminarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.preliminaryView?(shouldDisplayOnDayView: self) , shouldShow {
            if let preView = delegate.preliminaryView?(viewOnDayView: self) {
                preliminaryView?.removeFromSuperview()
                preliminaryView = preView
                weekView.insertSubview(preView, at: 0)
                preView.layer.zPosition = CGFloat(-MAXFLOAT)
            }
        }
        else {
            preliminaryView?.removeFromSuperview()
        }
    }
    
    public func supplementarySetup() {
        if let delegate = calendarView.delegate,
            let shouldShow = delegate.supplementaryView?(shouldDisplayOnDayView: self) ,
            shouldShow {
            if let supView = delegate.supplementaryView?(viewOnDayView: self) {
                supplementaryView?.removeFromSuperview()
                supplementaryView = supView
                insertSubview(supView, at: 0)
            }
        } else {
            supplementaryView?.removeFromSuperview()
            supplementaryView = nil
        }
    }

**Comment by DannyJi** [comment] 2017-01-03 21:12
@schulz89sp 

So I tried your changes (cut and replaced them in CVCalendarDayView) and then changed the following in ViewController.swift.

```
  func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
    if dayView.date.year == 2017 && dayView.date.month == 1 && dayView.date.day == 03 {
      print("03.01.2017")
      print(dayView.date.commonDescription)
      return true
    }
    return false
  }
```

I am not getting the same result!  I get 07 January 2017 marked.  When I use what @sry241 had for his test date (19-Jan-2017), I now get a different date circled than even an hour ago - I am getting the 17- Feb-2017.

Feel like each time I run this, I am getting a different date circled - even with your changes above.

I download the latest from Github.

Attached is with your additions and test date of (03-Jan-2017).  FYI, I see the console output with 

```
03.01.2017
3 January, 2017
```

![screen shot 2017-01-03 at 4 09 08 pm](https://cloud.githubusercontent.com/assets/5400889/21623147/0c6e9b56-d1cf-11e6-95b1-a5a1a281e706.png)

**Comment by DannyJi** [comment] 2017-01-03 21:21
@schulz89sp since we both made the same changes in CVCalendarDayView, but are seeing differences in running this in the supplied Demo (ViewController.swift) and your project's CalendarioController.swift - maybe there is a difference in how the calendar is initialized in your app compared to the Demo app.

**Comment by schulz89sp** [comment] 2017-01-03 21:29
Send your project at moretti_diego@hotmail.it

**Comment by DannyJi** [comment] 2017-01-03 21:37
Just sent now.  It is just the Demo as part of this project with your changes and a change in the ViewController.swift to circle just a specific date.

**Comment by schulz89sp** [comment] 2017-01-03 22:15
[CVCalendar-master-3.zip](https://github.com/Mozharovsky/CVCalendar/files/683348/CVCalendar-master-3.zip)

I tweaked the CVCalendarDayView and ViewController, removing the things that I do not need and do not use the type DataRange ...
So it works, then the problem must be in those functions ...
Developers take a look at my own version, perhaps adding the missing things one at a time, at the time that the problem solved.
I hope I was clear, I do not speak English.

**Comment by justinctlam** [comment] 2017-01-04 00:45
Let me investigate.

**Comment by justinctlam** [comment] 2017-01-04 06:33
@DannyJi @sry241 @schulz89sp 

Is this issue only occurring for you in the demo?

My investigation revealed that the center point for the circle path is not correct. The midX value is incorrectly calculated.  Can you try replacing the following line:

`let centrePoint: CGPoint = CGPoint(x: ringRect.midX, y: ringRect.midY)`

with this:
        
`let centrePoint = CGPoint(x: dayView.frame.width/2, y: dayView.frame.height/2)`

Ideally, the centrePoint for the path should be relative to the dayView(newView) cell not relative to the parent (weekView).

I don't think there is anything wrong with the API, just a problem with the drawing of the supplementary view in the demo.

Also, it is better to not compare dates as the time might be off when taking into account the time zones. It would be better to compare the month/year/day to ensure consistency.

**Comment by sry241** [comment] 2017-01-04 07:05
@justinctlam  
The issue is since the new swift 3 version (1.4.0). I work with the calendar for a year and before the swift 3 version everything was ok.

**Comment by justinctlam** [comment] 2017-01-04 07:11
I see. But can you try and see if the fix works for you or not?

**Comment by justinctlam** [comment] 2017-01-04 14:20
@sry241 
The introduction of the bug was commit 71c30da64669283e3d3230e866459f9d1ebf0605.
I fixed some of the issues in commit b99c909039f9bdfa27bfc965e5a97f52a53b25f2.

I have created a new pull request to fix the remaining issue.

**Comment by DannyJi** [comment] 2017-01-04 14:36
@justinctlam I was just typing up my response when I saw your post.

Yes.  I saw this in my own project when I first updated my pods.  I decided to reduce the issue in the supplied Demo.  So I have not gone back to my own project until we can squash this.

What I did today:
I downloaded a brand new copy of this project and did not touch the CVCalendarView swift files.  Instead I only modified the ViewController.swift.  I did change the centrePoint calculation as you requested

`let centrePoint = CGPoint(x: dayView.frame.width/2, y: dayView.frame.height/2)`

and changed the 

`func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool ` 

to "circle" just the date 03-Jan-2017.

Without any other modification, I do not even see a circle.  

I will wait for your fix.

********************************************************************

I would suggest that for the Demo that we set the 

`func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool`

to show a predictable date when launching.  For instance , it could always circle the 15th of the current month.  The Demo project right now has it randomly circled.  While this may look good and impressive, we have found is not accurate.  This would be a visual check every time someone uses and tests the Demo that the 15th, for instance, would be circled.

@justinctlam Thanks again for identifying and helping with the issue.

**Comment by schulz89sp** [comment] 2017-01-04 15:00
I with the fix:
let Centrepoint CGPoint = (x: dayView.frame.width / 2, y: dayView.frame.height / 2)
I also solved in CVCalendarDemo.

But I have noticed in your last comment:

@ sry241
The introduction of the bug was committed 71c30da.
I fixed some of the issues in commit b99c909. <--- This

I have created a new pull request to fix the remaining issue.

At line 604 of CVCalendarDayView it is not as you say here b99c909

          if selectionView! = nil {
             selectionView? .removeFromSuperview ()
              setSelectedWithType (.single)
          }

But when we download the example is as follows:

         if selectionView! = nil {
             selectionView? .removeFromSuperview ()
             let selectionType = calendarView.shouldSelectRange? CVSelectionType.range (.changed): CVSelectionType.single
             setSelectedWithType (selectionType)
         }

It's normal?

Thanks for the fix.

**Comment by justinctlam** [comment] 2017-01-04 15:18
@schulz89sp I don't quite understand your question.

b99c909 has the following as a fix:

`dayView.setNeedsLayout()`
 `dayView.layoutIfNeeded()`

Should we close this bug?

**Comment by schulz89sp** [comment] 2017-01-04 15:41
Then I doing the correction to the demo project I solved the bug saying @DannyJi, but I think he still has problems.
While I realized that scrolling down https://github.com/Mozharovsky/CVCalendar/commit/b99c909039f9bdfa27bfc965e5a97f52a53b25f2 file is written to the line 604 of CVCalendarDayView:

       if selectionView! = Nil {
          selectionView? .removeFromSuperview ()
           setSelectedWithType (.single)
       }

But When We download the example is as follows:

      if selectionView! = Nil {
          selectionView? .removeFromSuperview ()
          let selectionType = calendarView.shouldSelectRange? CVSelectionType.range (.changed): CVSelectionType.single
          setSelectedWithType (selectionType)

**Comment by justinctlam** [comment] 2017-01-05 09:45
@DannyJi Are you still having problems?

**Comment by DannyJi** [comment] 2017-01-05 14:41
@justinctlam I downloaded the latest copy after your commits and modified the Demo project so I could spot check and all seems to work now.  I will try in my own project and let you know if I have any issues.

**Comment by justinctlam** [comment] 2017-01-05 14:48
@DannyJi Feel free to make the change and submit a PR.

If this fixes your issue, I think we can close the bug now.

**Comment by DannyJi** [comment] 2017-01-05 16:35
@elsesiy @justinctlam I am a subversion users, do I just downloaded GitHub Desktop.

I cloned the project then made a branch in GitHub Desktop.

I made my changes in Xcode, and tested.

I committed my change.

When I used GitHub Desktop to create a Pull Request, I got "Authentication Failed: You may not have permission to access CVCalendar. Check Preferences to make sure you’re still logged in."

I am logged in to GitHub Desktop

I know this is beyond the scope of this bug, but not sure what I need to do to let you guys review it and merge.  I would like to contribute - just new to this.

**Comment by elsesiy** [comment] 2017-01-05 16:41
@DannyJi Since you're not allowed to push to the repository directly, you should first fork it off to your account, make the changes to your own repository and open up a so-called Pull Request.

**Comment by DannyJi** [comment] 2017-01-05 16:58
@elsesiy - thanks!  that's the magic sauce.  I created and looks like it worked.  Thanks for help.

**Comment by schulz89sp** [comment] 2017-01-06 00:28
Sorry I noticed something now then at exactly 1:24 AM.
The calendar marks the day as January 5, not as supplementaryView just as present day, it should be January 6th.

I solved by removing this piece of code:

    override func awakeFromNib() {
        let timeZoneBias = 480 // (UTC+08:00)
        currentCalendar = Calendar.init(identifier: .gregorian)
        if let timeZone = TimeZone.init(secondsFromGMT: -timeZoneBias * 60) {
            currentCalendar?.timeZone = timeZone }
        }

there is an error?

**Comment by justinctlam** [comment] 2017-01-06 03:32
@schulz89sp This is not an error. Make sure you are using the same calendar for any date calculations you are doing. This piece of code creates a calendar based on a timezone that is +8 hours from GMT. Everything in the demo should be using `currentCalendar`.

**Comment by schulz89sp** [comment] 2017-01-11 10:09
@justinctlam I have a question...
If I wanted to put an activity indicator in the calendar that appears when you change the month going to the right or to the left with your finger and not with the "forward" "back" ... should I put it in that way so that before him to make the circles the supplementary view?
I hope I was clear, I wanted to write to you in private but do not know how.
Thank you.

**Comment by justinctlam** [comment] 2017-01-12 00:21
@elsesiy Can we close this bug?
@schulz89sp Can you open a new issue to ask your question?

**Comment by elsesiy** [comment] 2017-01-12 18:03
@justinctlam I guess so :)

**Closed by elsesiy** 2017-01-12 18:03 UTC
