### ISSUE TITLE
fatal error change mode to weak view

### ISSUE THREAD

**Issue by Xc0d3dev** [Mozharovsky/CVCalendar#229] opened 2016-02-13 22:43 UTC
Hi, the problem it's on supplementaryView. When I want to change the Week View i get fatal error

Code function:

    func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        let dateformatter = NSDateFormatter()
        dateformatter.dateFormat = "yyyy/MM/dd"
        let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)
        let date_Array = ["2016/02/10","2016/02/11","2016/02/12"]
        for(var i=0;i<date_Array.count;i++)
        {
            if(date2==date_Array[i])
            {
                return true
            }
        }
        return false
    }
}

and error
```
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 

```
The error is on line
` let date2 = dateformatter.stringFromDate(dayView.date.convertedDate()!)`

**Comment by neugartf** [comment] 2016-02-14 14:02
This is a duplicate of #100. It's hopefully gonna be fixed in 2.0.0. Thank you!

**Closed by neugartf** 2016-02-14 14:02 UTC
Labels: duplicate

**Comment by Xc0d3dev** [comment] 2016-02-14 14:33
On CVCalendar 2.0 Develop the problem remains. 

How can I fix the problem

**Comment by neugartf** [comment] 2016-02-14 15:00
Yeah, that's all work in progress. Feel free to propose a PR.

**Comment by Xc0d3dev** [comment] 2016-02-15 06:38
Code fixed.

```
func supplementaryView(shouldDisplayOnDayView dayView: DayView) -> Bool {
        let dateformatter = NSDateFormatter()
        dateformatter.dateFormat = "yyyy-MM-dd"
        let date_Array = [[2016,02,10],[2016,02,11],[2016,02,12],[2016,01,11]]
        for(var i=0;i<date_Array.count;i++)
        {
        if let date = dayView.date {
            if(date.day == date_Array[i][2] && date.month == date_Array[i][1] && date.year == date_Array[i][0]) {
                return true
            }
        } else {

        }
    }
        return false
    }
```
