### ISSUE TITLE
Year is stuck on current year.

### ISSUE THREAD

**Issue by PanMluvci** [Mozharovsky/CVCalendar#403] opened 2016-12-13 19:26 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
Swipe in month 12 should change year *12/2016 -> 1/2017

## Current Behavior
Swipe in month 12 should change year *12/2016 -> 1/2016

## Your Environment
current released demo project

**Comment by PanMluvci** [comment] 2016-12-14 06:48
Whoa I just realized that if you go to *12/2016 -> 1/2016.... you cannot go back.... the 12 month is missing. This thing is buggy as hell. How can somebody released this and call it demo?

**Comment by elsesiy** [comment] 2016-12-14 10:52
@PanMluvci Feel free to fix the Demo project. The library works as intended, the demo is only meant to get a raw overview about the functioning.

**Comment by elsesiy** [comment] 2016-12-16 07:43
Fixed in 8fadc59

**Closed by elsesiy** 2016-12-16 07:43 UTC
Labels: bug
