### ISSUE TITLE
I want this feature: 1. User can select multiple dates 2. On long tapping a date it will ask for selecting the date range to get selected.

### ISSUE THREAD

**Issue by RIju912** [Mozharovsky/CVCalendar#295] opened 2016-05-25 11:57 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (Cocoapods spec):
* Device used i.e. iPhone 6S:
* Physical device (y/n):
* Link to your project (if available):

**Comment by zuaaef** [comment] 2016-05-25 12:18
What feature is that? Your question is a little confusing

**Comment by RIju912** [comment] 2016-05-25 14:49
is it clear @zuaaef

**Comment by zuaaef** [comment] 2016-05-25 18:34
If you want this feature URGENTLY then i suggest you use another calendar.
They have already said here --> https://github.com/Mozharovsky/CVCalendar/issues/138

That the feature is not yet available.

**Comment by RIju912** [comment] 2016-05-26 04:21
Can you please suggest another calendar name? or share the github link. Thanks in Adv. @zuaaef

**Comment by zuaaef** [comment] 2016-05-26 11:31
@RIju912 hmm. I did a search on cocoa pods and found  [this one](https://github.com/patchthecode/JTAppleCalendar). There is a tutorial on how to set it up [right here as well](https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial). It has the feature that you want.

**Comment by RIju912** [comment] 2016-05-26 14:42
not helping the requirements. :( @zuaaef

**Comment by zuaaef** [comment] 2016-05-26 16:28
@RIju912 my bad, you are right. It does have multiple date selection, but it does not have date range selection.

**Comment by RIju912** [comment] 2016-05-26 16:36
Or I will tap one date and tap on another date. like I am tapping on 5th and again tapping on 15th. total will get selected.and if dont want to select 10th and 12th I will double tap on that. but the rest of the range will get selected. How can I do this @zuaaef

**Comment by patchthecode** [comment] 2016-05-26 21:08
@RIju912 Which calendar are you talking about? CVCalendar? or the one i suggested?

**Comment by zuaaef** [comment] 2016-05-26 21:09
@RIju912 Which calendar are you talking about? CVCalendar? or the one i suggested?

**Comment by RIju912** [comment] 2016-05-27 02:30
I am talking about this requirement. "I will tap one date and tap on another date. like I am tapping on 5th and again tapping on 15th. total will get selected.and if dont want to select 10th and 12th I will double tap on that. but the rest of the range will get selected" . how to do?

**Comment by zuaaef** [comment] 2016-05-27 04:01
@RIju912 I do not know how to your requirement with CVCalendar.

**Comment by RIju912** [comment] 2016-05-27 04:05
:( @zuaaef

**Comment by elsesiy** [comment] 2016-09-02 06:59
Duplicate of #138

**Closed by elsesiy** 2016-09-02 06:59 UTC
